# Generated by Django 4.2.5 on 2023-10-18 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0007_alter_comment_posted_by"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
