# Generated by Django 4.2.5 on 2023-10-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0009_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="posted_by",
            field=models.CharField(default="haikal", max_length=100),
            preserve_default=False,
        ),
    ]
